require('dotenv').config();
const { Client, GatewayIntentBits, SlashCommandBuilder, EmbedBuilder, AttachmentBuilder } = require('discord.js');
const { GoogleGenerativeAI } = require('@google/generative-ai');
const axios = require('axios');
const fs = require('fs');

const client = new Client({
    intents: [
        GatewayIntentBits.Guilds,
        GatewayIntentBits.GuildMessages,
        GatewayIntentBits.MessageContent
    ]
});

const COOLDOWN_FILE = './cooldowns.json';
const gemini = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);

const SYSTEM_PROMPT = `Kamu adalah Roblox Luau Deobfuscator dan Code Improver terbaik.
Tugasmu:
- Deobfuscate script yang dikirim
- Bersihkan kode sepenuhnya (clean code, readable, modern style)
- Rename semua variable, function, dan table menjadi nama yang jelas dan deskriptif
- Perbaiki bug dan logic error
- Optimasi performa jika memungkinkan
- Tambahkan komentar yang membantu di bagian penting

Output harus dalam format berikut:

\`\`\`lua
-- [Cleaned & Improved Roblox Script]
-- Generated by AI Deobfuscator

[KODE LUA YANG SUDAH DIBERSIHKAN DAN DIPERBAIKI]
\`\`\`

Penjelasan perubahan yang dilakukan.`;

// ================== COOLDOWN ==================
function getCooldowns() {
    if (!fs.existsSync(COOLDOWN_FILE)) return {};
    return JSON.parse(fs.readFileSync(COOLDOWN_FILE, 'utf8'));
}

function saveCooldown(userId) {
    const cooldowns = getCooldowns();
    cooldowns[userId] = Date.now();
    fs.writeFileSync(COOLDOWN_FILE, JSON.stringify(cooldowns, null, 2));
}

function isOnCooldown(userId) {
    if (userId === process.env.OWNER_ID) return false;
    const cooldowns = getCooldowns();
    const lastUsed = cooldowns[userId];
    if (!lastUsed) return false;
    return Date.now() - lastUsed < 24 * 60 * 60 * 1000;
}

// ================== PROCESS WITH 3 AI ==================
async function processWithAI(code) {
    const providers = ['gemini', 'grok', 'deepseek'];
    
    for (const provider of providers) {
        try {
            let result;
            if (provider === 'gemini') {
                const model = gemini.getGenerativeModel({ model: "gemini-1.5-flash" });
                const res = await model.generateContent([SYSTEM_PROMPT, `Script Roblox Luau:\n\n${code}`]);
                result = res.response.text();
            } 
            else if (provider === 'grok') {
                const res = await axios.post('https://api.x.ai/v1/chat/completions', {
                    model: "grok-beta",
                    temperature: 0.2,
                    max_tokens: 8192,
                    messages: [
                        { role: "system", content: SYSTEM_PROMPT },
                        { role: "user", content: `Deobfuscate dan improve script Roblox ini:\n\n${code}` }
                    ]
                }, { headers: { Authorization: `Bearer ${process.env.GROK_API_KEY}` }});
                result = res.data.choices[0].message.content;
            } 
            else if (provider === 'deepseek') {
                const res = await axios.post('https://api.deepseek.com/v1/chat/completions', {
                    model: "deepseek-chat",
                    temperature: 0.2,
                    max_tokens: 8192,
                    messages: [
                        { role: "system", content: SYSTEM_PROMPT },
                        { role: "user", content: `Deobfuscate dan improve script Roblox ini:\n\n${code}` }
                    ]
                }, { headers: { Authorization: `Bearer ${process.env.DEEPSEEK_API_KEY}` }});
                result = res.data.choices[0].message.content;
            }
            if (result) return result;
        } catch (err) {
            console.log(`[${provider.toUpperCase()}] Error: ${err.message}`);
        }
    }
    return null;
}

// ================== AUTO DETECT ATTACHMENT ==================
client.on('messageCreate', async message => {
    if (message.author.bot) return;

    const attachment = message.attachments.first();
    if (!attachment) return;

    const filename = attachment.name.toLowerCase();
    if (!filename.endsWith('.lua') && !filename.endsWith('.luau') && !filename.endsWith('.txt')) return;

    if (isOnCooldown(message.author.id)) {
        return message.reply({ content: "❌ Kamu hanya boleh memproses **1 script setiap 24 jam**.", ephemeral: true });
    }

    const loading = await message.reply('🔄 Sedang memproses script menggunakan 3 AI...');

    try {
        const res = await axios.get(attachment.url, { responseType: 'text' });
        const result = await processWithAI(res.data);

        if (!result) {
            return loading.edit('❌ Gagal memproses script. Semua API mengalami error.');
        }

        saveCooldown(message.author.id);

        const outputFile = new AttachmentBuilder(Buffer.from(result), {
            name: 'cleaned_' + filename.replace('.txt', '.lua')
        });

        const embed = new EmbedBuilder()
            .setTitle('✅ Deobfuscation Berhasil')
            .setColor('Green')
            .setDescription(`Script dari **${message.author.tag}** telah dibersihkan.`)
            .setTimestamp();

        await loading.delete();
        await message.reply({ embeds: [embed], files: [outputFile] });

    } catch (error) {
        console.error(error);
        await loading.edit('❌ Terjadi kesalahan saat memproses file.');
    }
});

// ================== SLASH COMMAND (Manual) ==================
client.on('interactionCreate', async interaction => {
    if (!interaction.isCommand() || interaction.commandName !== 'deobfuscate') return;

    const attachment = interaction.options.getAttachment('file');
    if (!attachment) return interaction.reply({ content: 'File tidak ditemukan!', ephemeral: true });

    await interaction.deferReply();

    const filename = attachment.name.toLowerCase();
    if (!filename.endsWith('.lua') && !filename.endsWith('.luau') && !filename.endsWith('.txt')) {
        return interaction.editReply('❌ Hanya mendukung file `.lua`, `.luau`, atau `.txt`');
    }

    if (isOnCooldown(interaction.user.id)) {
        return interaction.editReply('❌ Kamu hanya boleh memproses 1 script setiap 24 jam.');
    }

    try {
        const res = await axios.get(attachment.url, { responseType: 'text' });
        const result = await processWithAI(res.data);

        if (!result) return interaction.editReply('❌ Semua AI gagal memproses script.');

        saveCooldown(interaction.user.id);

        const file = new AttachmentBuilder(Buffer.from(result), {
            name: 'cleaned_' + filename.replace('.txt', '.lua')
        });

        await interaction.editReply({
            content: '✅ Berhasil memproses script!',
            files: [file]
        });
    } catch (err) {
        await interaction.editReply('❌ Terjadi error saat memproses.');
    }
});

client.once('ready', () => {
    console.log(`✅ Bot ${client.user.tag} telah aktif!`);
    console.log(`🔥 Mode: Auto-Scan + Slash Command`);
    console.log(`⏳ Cooldown: 1 script / 24 jam per user`);
});

client.login(process.env.TOKEN);
